#!/bin/bash
echo "Start now --> ""${VERSION}"

cd /root/workspace 
rm -rf docs
mv /root/clone/docs .
rm -rf website-docs
mv /root/clone/website-docs .
rm -rf website-log
mv /root/clone/website-log .

rm -rf ./website-docs/public/install/${VERSION}
mkdir -p ./website-docs/public/install/${VERSION}
cp -r ./docs/install/* ./website-docs/public/install/${VERSION}/
if [ ${VERSION} == "master" ];then
    cp -r ./docs/resource/release/release_list_* ./website-docs/public/more/
fi

# shellcheck disable=SC2034
BUILD_PATH=${VERSION}
#!/bin/bash
# shellcheck disable=SC2120
function delete_old() {
  local buildPath="/root/workspace/docs/tools/generate_html/${BUILD_PATH}/output$1"
  # shellcheck disable=SC2045
  for dir in $(ls "$buildPath"); do
    # shellcheck disable=SC2034
    local next="$1"/"$dir"
    local dirPath="$buildPath"/"$dir"

    if [ ! -d "$dirPath" ]; then
      continue
    fi
    #    echo "$dirPath"
    # shellcheck disable=SC2155
    local in=$(awk -v a="$dirPath" -v b="/en/" 'BEGIN{print index(a,b)}')
    # shellcheck disable=SC2170
    # shellcheck disable=SC2071
    if [ "$in" -gt 0 ]; then
      local inz=${dirPath:in+3}
      # shellcheck disable=SC2155
      local k=$(awk -v a="$inz" -v b="/" 'BEGIN{print index(a,b)}')
      if [ "$k" == 0 ]; then
        refreshDir "$next"
      fi
    fi

    # shellcheck disable=SC2155
    local on=$(awk -v a="$dirPath" -v b="/zh-CN/" 'BEGIN{print index(a,b)}')
    # shellcheck disable=SC2170
    # shellcheck disable=SC2071
    if [ "$on" -gt 0 ]; then
      local onz=${dirPath:on+6}
      # shellcheck disable=SC2155
      local k=$(awk -v a="$onz" -v b="/" 'BEGIN{print index(a,b)}')
      if [ "$k" == 0 ]; then
        refreshDir "$next"
      fi
    fi
    delete_old "$next"
  done
}

function refreshDir() {
  local path=$1
  echo "$path"
  rm -rf "/root/workspace/website-docs/public"$1

  mkdir -p "/root/workspace/website-docs/public"$1

  cp -r /root/workspace/docs/tools/generate_html/${BUILD_PATH}/output"$path"/* /root/workspace/website-docs/public"$path"/
}


# shellcheck disable=SC2164
cd /root/workspace
if [ ${DO_BUILD} == "true" ];then
  # shellcheck disable=SC2164
  cd ./docs/tools/generate_html
  if [ ${VERSION} == "master" ];then
    # shellcheck disable=SC2034
    BUILD_PATH="daily"
    python run.py --user="${USER}" --pd="${PD}" --wgetdir="${WGETDIR}" --theme="/root/workspace/website-docs/template"
 --single_generate="${SINGLE_GENERATE}"
  else
    python run.py --version="${VERSION}" --user="${USER}" --pd="${PD}" --wgetdir="${WGETDIR}" --release_url="${RELEASE_URL}" --theme="/root/workspace/website-docs/template"  --single_generate="${SINGLE_GENERATE}"
  fi

  # shellcheck disable=SC2164
  cd /root/workspace/docs/tools/generate_html/${BUILD_PATH}/output
  cp -f common.css /root/workspace/website-docs/public/
  cp -f common.js /root/workspace/website-docs/public/
  cp -f config.json /root/workspace/website-docs/public/
  cp -f docs-menu.json /root/workspace/website-docs/public/
  cp -f header.json /root/workspace/website-docs/public/
  cp -f msVersion.json /root/workspace/website-docs/public/

  delete_old
fi

if [ ${REPLACE_BUILD} == "true" ];then
    cd /root/workspace/website-docs/scripts
    python distrib_json.py --version="all"
fi

# shellcheck disable=SC2164
cd /root/workspace/website-docs

git config --global user.email "contact@mindspore.cn"

git config --global user.name "MindSpore"

git config core.ignorecase false

git add -A

git commit -m "Update website files generated by mindspore && docs repo"

git push

sleep 3m

cd /root/workspace/website-log

cp /log/* ./log

find ./log -name "`date -d "1 month ago" +%Y-%m`*.*" -exec rm -Rf {} \;

git add -A

git commit -m "new log"

git push

echo "success!!!!!!"
